name: Check Commit Message Format

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Check-Commit-Message-Format:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message Format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
